<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <gazebo>

    <!-- turn on self-collision detection so that links will not pass through each other -->
    <self_collide>1</self_collide>


    
    <!-- for the mobile base -->
    <!-- MQMX to (possibly?) replace this with ros control plugin -->
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <leftJoint>wheel_2_joint</leftJoint>
      <rightJoint>wheel_5_joint</rightJoint>
      <robotBaseFrame>chassis</robotBaseFrame>
      <wheelSeparation>${chassis_width - wheel_thickness}</wheelSeparation>
      <wheelDiameter>${2 * wheel_radius}</wheelDiameter>
      <publishWheelJointState>true</publishWheelJointState>
      <legacyMode>false</legacyMode>
    </plugin>


    
    <!-- for the UR10, copied from $(find ur_description)/urdf/common.gazebo.xacro -->
    <plugin name="ros_control" filename="libgazebo_ros_control.so">
      <!--robotNamespace>/</robotNamespace-->
      <!--robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType-->
    </plugin>
    
    <!--
	<plugin name="gazebo_ros_power_monitor_controller" filename="libgazebo_ros_power_monitor.so">
	<alwaysOn>true</alwaysOn>
	<updateRate>1.0</updateRate>
	<timeout>5</timeout>
	<powerStateTopic>power_state</powerStateTopic>
	<powerStateRate>10.0</powerStateRate>
	<fullChargeCapacity>87.78</fullChargeCapacity>     
	<dischargeRate>-474</dischargeRate>
	<chargeRate>525</chargeRate>
	<dischargeVoltage>15.52</dischargeVoltage>
	<chargeVoltage>16.41</chargeVoltage>
	</plugin>
    -->
  </gazebo>

</robot>
